const cfg=window.ARHS_CONFIG||{};const configured=!cfg.SUPABASE_URL.includes("PASTE_");const sb=configured?supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY):null;
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(Number(n)||0);
let state={leads:[],jobs:[],estimates:[],invoices:[]};
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-tab]').forEach(x=>x.classList.remove('active'));b.classList.add('active');['dashboard','leads','jobs','estimates','invoices','photos'].forEach(id=>document.getElementById(id).classList.toggle('hidden',id!==b.dataset.tab))});
async function load(){if(!sb){alert('Add Supabase keys in config.js first.');return}for(const t of Object.keys(state)){const {data}=await sb.from(t).select('*').order('created_at',{ascending:false});state[t]=data||[]}render()}
function render(){newLeads.textContent=state.leads.filter(x=>x.status==='New').length;openEstimates.textContent=state.estimates.filter(x=>!['Approved','Declined'].includes(x.status)).length;outstanding.textContent=money(state.invoices.reduce((a,x)=>a+Number(x.balance||0),0));reviews.textContent=state.invoices.filter(x=>x.status==='Paid'&&!x.review_requested).length;
leadList.innerHTML=state.leads.map(x=>`<div class="row"><div><b>${x.name}</b><div>${x.service||''}</div></div><div>${x.status}</div><div>${money(x.estimated_value)}</div><button class="secondary">Open</button></div>`).join('');
jobList.innerHTML=state.jobs.map(x=>`<div class="row"><div><b>${x.customer_name}</b><div>${x.service||''}</div></div><div>${x.job_date||''} ${x.job_time||''}</div><div>${x.status}</div><button class="secondary" onclick="downloadICS('${x.id}')">Add to Calendar</button></div>`).join('');
estimateList.innerHTML=state.estimates.map(x=>`<div class="row"><div><b>${x.customer_name}</b><div>${x.estimate_number||''}</div></div><div>${x.status}</div><div>${money(x.amount)}</div><button class="btn" onclick="convertEstimate('${x.id}')">Convert</button></div>`).join('');
invoiceList.innerHTML=state.invoices.map(x=>`<div class="row"><div><b>${x.customer_name}</b><div>${x.invoice_number||''}</div></div><div>${x.status}</div><div>${money(x.balance)}</div><button class="secondary" onclick="markReview('${x.id}')">${x.review_requested?'Review Sent':'Send Review'}</button></div>`).join('')}
async function convertEstimate(id){const e=state.estimates.find(x=>x.id===id);if(!e)return;await sb.from('invoices').insert({customer_name:e.customer_name,service:e.service,amount:e.amount,balance:e.amount,status:'Draft',invoice_number:'INV-'+Date.now()});await sb.from('estimates').update({status:'Approved'}).eq('id',id);load()}
async function markReview(id){await sb.from('invoices').update({review_requested:true}).eq('id',id);load()}
function downloadICS(id){const j=state.jobs.find(x=>x.id===id);if(!j)return;const d=(j.job_date||'').replaceAll('-','');const ics=`BEGIN:VCALENDAR\nVERSION:2.0\nBEGIN:VEVENT\nDTSTART:${d}T130000\nSUMMARY:${j.customer_name} - ${j.service||'Job'}\nDESCRIPTION:ARHS Office job\nEND:VEVENT\nEND:VCALENDAR`;const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([ics],{type:'text/calendar'}));a.download='arhs-job.ics';a.click()}
load();